### ISSUE TITLE
Default configuration doesn't work

### ISSUE THREAD

**Issue by tengrism** [Azure-Samples/mipsdk-filesdk-java-sample#9]
Hello!

I have compiled java sample and created Application Registration in Azure AD with corresponding premissions, according to instructions. I have amended code

        appInfo.setApplicationId("xxxxx-xxxx-xxxx-xxxx-xxxxxxxx");
        appInfo.setApplicationName("MIP SDK Java Sample");
        appInfo.setApplicationVersion("1.10"); 

but it give error about token. Firewall is disabled. Any idea?

PS C:\> java -jar mipsdksample.jar
Enter a username: tengrism@tengrism.onmicrosoft.com
Error reading data from file: null
java.lang.RuntimeException: java.lang.NullPointerException
        at com.microsoft.mipsdksample.TokenCacheAspect.readDataFromFile(TokenCacheAspect.java:63)
        at com.microsoft.mipsdksample.TokenCacheAspect.<init>(TokenCacheAspect.java:41)
        at com.microsoft.mipsdksample.AuthDelegateImpl.acquireTokenInteractive(AuthDelegateImpl.java:80)
        at com.microsoft.mipsdksample.AuthDelegateImpl.acquireToken(AuthDelegateImpl.java:67)
        at com.microsoft.informationprotection.internal.NativeAuthDelegate.AcquireOAuth2Token(NativeAuthDelegate.java:21)
        at com.microsoft.informationprotection.internal.gen.SdkWrapperJNI.SwigDirector_AuthDelegate_AcquireOAuth2Token__SWIG_0(SdkWrapperJNI.java:1958)
Caused by: java.lang.NullPointerException
        at com.microsoft.mipsdksample.TokenCacheAspect.readDataFromFile(TokenCacheAspect.java:60)
        ... 5 more
Error reading data from file: null
java.lang.RuntimeException: java.lang.NullPointerException
        at com.microsoft.mipsdksample.TokenCacheAspect.readDataFromFile(TokenCacheAspect.java:63)
        at com.microsoft.mipsdksample.TokenCacheAspect.<init>(TokenCacheAspect.java:41)
        at com.microsoft.mipsdksample.AuthDelegateImpl.acquireTokenInteractive(AuthDelegateImpl.java:80)
        at com.microsoft.mipsdksample.AuthDelegateImpl.acquireToken(AuthDelegateImpl.java:67)
        at com.microsoft.informationprotection.internal.NativeAuthDelegate.AcquireOAuth2Token(NativeAuthDelegate.java:21)
        at com.microsoft.informationprotection.internal.gen.SdkWrapperJNI.SwigDirector_AuthDelegate_AcquireOAuth2Token__SWIG_0(SdkWrapperJNI.java:1958)
Caused by: java.lang.NullPointerException
        at com.microsoft.mipsdksample.TokenCacheAspect.readDataFromFile(TokenCacheAspect.java:60)
        ... 5 more
Exception in thread "main" java.util.concurrent.ExecutionException: com.microsoft.informationprotection.internal.gen.Error: NoAuthTokenError: Client application failed to provide authentication token for HTTP request.
        at java.util.concurrent.CompletableFuture.reportGet(Unknown Source)
        at java.util.concurrent.CompletableFuture.get(Unknown Source)
        at com.microsoft.mipsdksample.Action.CreateFileEngine(Action.java:105)
        at com.microsoft.mipsdksample.Action.<init>(Action.java:78)
        at com.microsoft.mipsdksample.App.main(App.java:54)
Caused by: com.microsoft.informationprotection.internal.gen.Error: NoAuthTokenError: Client application failed to provide authentication token for HTTP request.
        at com.microsoft.informationprotection.internal.gen.SdkWrapperJNI.SwigDirector_FileProfile_Observer_OnAddEngineFailure(SdkWrapperJNI.java:2315)

**Comment by makushima** [comment]
As you see, it is not solvable for a long time. It is obvious that MIP SDK currently supported only by Chinese cloud providers. You need to migrate to them, as they provide high quality support and quick response to all issues.

**Comment by saurabhsingla786** [comment]
Hi Team, Did anyone of you find any solution to this ?
